var TelegramBot = require('node-telegram-bot-api'),
    // Be sure to replace YOUR_BOT_TOKEN with your actual bot token on this line.
    telegram = new TelegramBot("311538848:AAHUlTcAQQJZCf3VOsq16OdBJcE-mcXnP30", { polling: true });
var rules = "Hentai, Yiff, MLP y más \n\nEste grupo es NSFW, o sea con contenido para adultos, pero se prohíbe el Gore o imágenes fuertes ya que pueden herir la sensibilidad de algunos. \n\nReglas del grupo: \n\n-Contenido permitido: \nPorno \nPacks Reales \nYiff \nPokefilia \nYaoi* \nHetero \nYuri \nVore* \nBDSM \nClop \nTrap* \nEntre otros \n\n*No enviar demasiado Ya que no son temas del agrado de todos. \n\n-Contenido Prohibido: \nGore \nCP* \nGrimdark \nImágenes Fuertes \nO por el estilo \n\nCompartir este tipo de contenido es Ban Automático y permanente \n\n-El Spam está prohibido. \n\nLas cadenas y Spam están completamente prohibidas en el grupo, son molestas y dañan a este, a la primera serás baneado permanentemente, sin excepción, quedas advertido \n\n°En el caso de los Memes \n\nEnviar más de 10 memes/momos seguidos será considerado como Spam, cada integrante tendrá 3 advertencias, si gasta el total de ellas, este será Baneado Permanentemente del grupo por Spammer. \n\n-Tener una buena convivencia. \n\nNo se enojen por todo, las cosas se pueden arreglar conversando; en dado caso de que esto se salga de control los administradores mismos se encargaran del caso. \n\n-Evitar comportamiento troll, castroso, buscapleito, grasoso, holkero o molesto (como pedir imágenes o exigir contenido sin aportar al grupo nada). \n\n-No se permite el rol en exceso \n\n-Se permiten los memes pero no lanzar 10 o 15 de golpe o se considerará como spam. \n\n-Se permite el autismo, pero de manera sana y respetuosa. \n\n-No enviar audios o videos troll (como gemidos). \n\n-Si envías una captura, específica porque lo envias y para qué, en caso contrario será considerado spam. \n\n°No ser inactivo, se dará ban a aquellos que:  \nA.- No muestren actividad en la semana (los lunes hay limpieza).\nB.- Sólo están aquí para robar material, (sin aportar nada al grupo). \nC.- No hablar ni aportar contenido. \n\n-Si el consentimiento es mutuo las nudes son por inbox, nada en el grupo, si envías tú Pack por el grupo es Ban. \n\n-No se permite el hostigamiento a los integrantes del grupo. \n\nYa sea en caso de hombres y mujeres, no se permite coquetear dentro del grupo ni molestar a los integrantes del mismo, no queremos Jotes o Buitres. \n\nHabrá una cantidad de 3 advertencias, a la 3 vez es Ban. \n\nEnlaces de otros grupos \n\nProhibido el Spam de estos, no se permite que compartan enlaces de grupos que sean idénticos a este, los administradores decidirán cuales son correctos, pregunten antes de enviar los enlaces.\n\n-Disfruta tu estadía en el grupo. \n\nAtte el Staff. \n\nReglas By. @JohnWolfShepard"

telegram.on("text", (message) => {
  if(message.text.toLowerCase().indexOf("/rules") === 0){
  telegram.sendMessage(message.chat.id, "Hola, te recuerdo que las reglas son: " + rules + " Gracias.");

  }
  });